LANGUAGES = {
    "pt-br": "PT-BR",
    "en-US": "EN",
    "es-ES": "ES",
}


DEFAULT_LANGUAGE = "pt-br"


TRANSLATIONS = {
    "pt-br": {
        "nav_festival": "Festival",
        "nav_restaurants": "Restaurantes",
        "nav_apply": "Inscricao",
        "nav_admin": "Admin",
        "cta_apply": "Inscrever meu restaurante",
        "cta_how": "Como funciona",
        "official_badge": "Participante Oficial",
        "view_restaurant": "Ver restaurante",
        "view_map": "Ver no mapa",
        "contact": "Entrar em contato",
        "restaurants_title": "Restaurantes participantes",
        "restaurants_empty": "Os restaurantes aprovados aparecerao aqui em breve.",
        "apply_title": "Inscricao de restaurante",
        "thank_you_title": "Inscricao recebida com sucesso.",
        "thank_you_text": "A organizacao entrara em contato apos a curadoria.",
        "terms": "Termos",
        "privacy": "Privacidade",
        "festival_edition": "Georgia Edition 2026",
        "homepage_title": "Flavors of Brazil Food Festival Georgia Edition 2026",
        "homepage_description": "Festival gastronomico brasileiro na Georgia reunindo restaurantes, sabores, cultura e experiencias culinarias brasileiras.",
        "hero_title": "Flavors of Brazil Food Festival - Georgia Edition 2026",
        "hero_subtitle": "Uma experiencia gastronomica brasileira na Georgia",
        "hero_text": "Um circuito gastronomico que reune restaurantes brasileiros para celebrar sabores, cultura e identidade, conectando a comunidade local a novas experiencias culinarias.",
        "about_text": "O Flavors of Brazil Food Festival e um circuito gastronomico que reune restaurantes brasileiros na regiao da Georgia, com o objetivo de promover a culinaria nacional, gerar visibilidade e fortalecer a presenca da comunidade gastronomica brasileira. Esta primeira edicao tera carater promocional e colaborativo, sem competicao, votacao ou ranking.",
        "dates_tbd": "Datas a definir",
        "footer_contact": "Contato",
        "footer_social": "Redes sociais",
        "footer_legal": "Legal",
        "footer_rights": "Todos os direitos reservados.",
        "menu_open": "Abrir menu",
        "hero_scroll": "scroll",
        "stat_days": "Dias",
        "stat_restaurants": "Restaurantes",
        "stat_brazilian": "Gastronomia Brasileira",
        "about_label": "Sobre o festival",
        "about_title": "Um circuito brasileiro na Georgia",
        "objectives_label": "Objetivos",
        "objectives_title": "Visibilidade, cultura e comunidade",
        "objective_promote_title": "Promover",
        "objective_promote_text": "A gastronomia brasileira na Georgia.",
        "objective_expand_title": "Ampliar",
        "objective_expand_text": "A exposicao dos restaurantes participantes.",
        "objective_media_title": "Gerar midia",
        "objective_media_text": "Conteudo digital, redes sociais e divulgacao editorial.",
        "objective_position_title": "Posicionar",
        "objective_position_text": "Restaurantes como referencia dentro da comunidade.",
        "why_label": "Por que participar",
        "why_title": "Uma vitrine comercial para restaurantes brasileiros",
        "why_1": "Mais visibilidade para seu negocio",
        "why_2": "Atracao de novos clientes",
        "why_3": "Divulgacao em midia e redes sociais",
        "why_4": "Fortalecimento da marca do restaurante",
        "why_5": "Certificado oficial de participacao",
        "why_6": "Presenca no website oficial do festival",
        "who_label": "Quem pode participar",
        "who_title": "Negocios legalizados na Georgia",
        "who_1": "Restaurantes brasileiros",
        "who_2": "Bares",
        "who_3": "Cafes",
        "who_4": "Padarias",
        "who_5": "Docerias",
        "who_6": "Food trucks",
        "how_label": "Como funciona",
        "how_title": "Etapas simples para entrar no circuito",
        "how_duration": "Duracao prevista: aproximadamente 20 dias / 3 a 4 semanas.",
        "step_create_title": "Criar",
        "step_create_text": "O restaurante cria um prato ou menu especial.",
        "step_define_title": "Definir",
        "step_define_text": "Define um preco fixo para a experiencia.",
        "step_offer_title": "Oferecer",
        "step_offer_text": "Disponibiliza o prato durante todo o periodo do festival.",
        "step_promote_title": "Divulgar",
        "step_promote_text": "Usa os materiais oficiais como participante.",
        "step_receive_title": "Receber",
        "step_receive_text": "Recebe clientes e ganha visibilidade.",
        "services_label": "Servicos incluidos",
        "services_title": "Conteudo, website e certificado",
        "service_1": "Producao de 1 video no restaurante mostrando o prato do festival.",
        "service_2": "Publicacao de conteudo nas redes sociais da Business News TV e Viver Magazine.",
        "service_3": "Insercao do restaurante na pagina oficial do festival.",
        "service_4": "Certificado oficial de participacao.",
        "service_5": "Conteudos digitais como posts, stories e reels.",
        "media_label": "Producao de conteudo",
        "media_title": "Captacao agendada no restaurante",
        "media_text": "A organizacao realizara a captacao de video no restaurante em data previamente agendada. O conteudo produzido podera ser utilizado em redes sociais, materiais promocionais e divulgacao institucional do festival.",
        "certificate_label": "Certificado",
        "certificate_title": "Certificado Oficial de Participacao",
        "certificate_text": "Todos os participantes aprovados receberao Certificado Oficial de Participacao do Flavors of Brazil Food Festival - Georgia Edition. O certificado sera emitido por Business News TV e Viver Magazine.",
        "responsibilities_label": "Responsabilidades",
        "responsibilities_title": "Compromissos do restaurante participante",
        "responsibility_1": "Manter o prato/menu disponivel durante todo o festival.",
        "responsibility_2": "Garantir qualidade e consistencia do produto.",
        "responsibility_3": "Informar corretamente preco e descricao.",
        "responsibility_4": "Utilizar os materiais oficiais do festival.",
        "responsibility_5": "Colaborar com a divulgacao.",
        "fee_label": "Taxa de participacao",
        "fee_title": "US$650 por restaurante",
        "fee_text": "Taxa unica de participacao. O pagamento sera solicitado apos aprovacao da inscricao.",
        "process_label": "Processo de inscricao",
        "process_title": "Da aplicacao a divulgacao",
        "process_1": "Preencher formulario de inscricao no site.",
        "process_2": "Enviar informacoes do prato/menu.",
        "process_3": "Passar por curadoria.",
        "process_4": "Pagar a taxa de inscricao.",
        "process_5": "Receber confirmacao.",
        "process_6": "Comecar a divulgar.",
        "schedule_label": "Cronograma",
        "schedule_title": "Datas a definir",
        "schedule_applications_label": "Abertura das inscricoes",
        "schedule_production_label": "Periodo de producao de conteudo",
        "schedule_start_label": "Inicio do festival",
        "schedule_end_label": "Encerramento",
        "restaurants_label": "Circuito Gastronomico",
        "restaurants_page_text": "Casas aprovadas pela curadoria do Flavors of Brazil Food Festival - Georgia Edition 2026.",
        "contact_label": "Contato",
        "contact_title": "Fale com a organizacao",
        "back_home": "Voltar ao site",
        "legal_label": "Legal",
        "terms_title": "Termos de participacao",
        "terms_1": "A inscricao esta sujeita a curadoria da organizacao do Flavors of Brazil Food Festival - Georgia Edition 2026.",
        "terms_2": "A taxa de participacao sera solicitada somente apos aprovacao da inscricao.",
        "terms_3": "O uso da marca do festival e restrito aos participantes aprovados e confirmados.",
        "terms_4": "A organizacao pode aprovar ou recusar inscricoes de acordo com criterios editoriais, comerciais e operacionais.",
        "terms_5": "O descumprimento das diretrizes de participacao pode resultar em exclusao do festival.",
        "terms_6": "O festival tem carater promocional e colaborativo, sem votacao, ranking ou competicao publica.",
        "privacy_title": "Politica de privacidade",
        "privacy_1": "Os dados enviados no formulario serao usados para avaliacao da inscricao, curadoria, comunicacao com responsaveis e operacao do festival.",
        "privacy_2": "Dados dos restaurantes aprovados, como nome, endereco, telefone, website, Instagram, horario de funcionamento, prato, descricao, preco e imagens, poderao ser publicados no site oficial.",
        "privacy_3": "Imagens, videos e informacoes do restaurante ou do prato poderao ser usados para divulgacao do Flavors of Brazil Food Festival - Georgia Edition 2026.",
        "privacy_4": "Dados sensiveis de acesso administrativo nao sao publicados e devem ser mantidos em variaveis de ambiente seguras.",
        "apply_intro": "Preencha os dados do responsavel, do restaurante e do prato/menu especial para passar pela curadoria.",
        "responsible_data": "Dados do responsavel",
        "restaurant_data": "Dados do restaurante",
        "dish_data": "Informacoes do prato/menu",
        "required_acceptances": "Aceites obrigatorios",
        "full_name": "Nome completo",
        "role": "Cargo/funcao",
        "phone": "Telefone",
        "email": "E-mail",
        "restaurant_name": "Nome do restaurante",
        "business_type": "Tipo de negocio",
        "select_option": "Selecione",
        "full_address": "Endereco completo",
        "city": "Cidade",
        "state": "Estado",
        "zip_code": "ZIP code",
        "business_phone": "Telefone comercial",
        "website": "Website",
        "instagram": "Instagram",
        "facebook": "Facebook",
        "business_hours": "Horario de funcionamento",
        "legal_question": "O negocio esta legalizado e em funcionamento na Georgia?",
        "dish_name_label": "Nome do prato ou menu especial",
        "fixed_price": "Preco fixo",
        "category": "Categoria",
        "available_question": "O prato estara disponivel durante todo o festival?",
        "dish_description_label": "Descricao do prato/menu",
        "main_ingredients": "Ingredientes principais",
        "allergens_label": "Contem alergenos?",
        "dish_upload": "Upload de foto do prato",
        "additional_notes": "Observacoes adicionais",
        "submit_application": "Enviar inscricao",
        "accept_truth_text": "Confirmo que as informacoes fornecidas sao verdadeiras.",
        "accept_curation_text": "Confirmo que o restaurante podera passar por curadoria antes da aprovacao.",
        "accept_fee_text": "Entendo que a taxa de participacao e de US$650 por restaurante.",
        "accept_brand_text": "Entendo que o uso da marca do festival e restrito aos participantes aprovados.",
        "accept_media_text": "Autorizo o uso de imagens, videos e informacoes do restaurante/prato para divulgacao do festival.",
        "accept_responsibilities_text": "Concordo com as responsabilidades do restaurante participante.",
        "yes": "Sim",
        "no": "Nao",
        "undefined": "A definir",
        "address": "Endereco",
        "hours": "Horario",
        "business_Restaurante": "Restaurante",
        "business_Bar": "Bar",
        "business_Cafe": "Cafe",
        "business_Padaria": "Padaria",
        "business_Doceria": "Doceria",
        "business_Food truck": "Food truck",
        "business_Outro": "Outro",
        "dish_Prato principal": "Prato principal",
        "dish_Lanche": "Lanche",
        "dish_Sobremesa": "Sobremesa",
        "dish_Bebida": "Bebida",
        "dish_Combo": "Combo",
        "dish_Outro": "Outro",
        "error_required": "Campo obrigatorio.",
        "error_email": "Informe um e-mail valido.",
        "error_business_type": "Selecione um tipo valido.",
        "error_dish_category": "Selecione uma categoria valida.",
        "error_yes_no": "Selecione Sim ou Nao.",
        "error_accept": "Aceite obrigatorio.",
        "error_upload_image": "Envie uma imagem JPG, PNG ou WebP.",
    },
    "en-US": {
        "nav_festival": "Festival",
        "nav_restaurants": "Restaurants",
        "nav_apply": "Apply",
        "nav_admin": "Admin",
        "cta_apply": "Register my restaurant",
        "cta_how": "How it works",
        "official_badge": "Official Participant",
        "view_restaurant": "View restaurant",
        "view_map": "View on map",
        "contact": "Contact",
        "restaurants_title": "Participating restaurants",
        "restaurants_empty": "Approved restaurants will appear here soon.",
        "apply_title": "Restaurant application",
        "thank_you_title": "Application received successfully.",
        "thank_you_text": "The organization will contact you after curation.",
        "terms": "Terms",
        "privacy": "Privacy",
        "festival_edition": "Georgia Edition 2026",
        "homepage_title": "Flavors of Brazil Food Festival Georgia Edition 2026",
        "homepage_description": "Brazilian food festival in Georgia bringing together restaurants, flavors, culture, and Brazilian culinary experiences.",
        "hero_title": "Flavors of Brazil Food Festival - Georgia Edition 2026",
        "hero_subtitle": "A Brazilian culinary experience in Georgia",
        "hero_text": "A dining circuit that brings Brazilian restaurants together to celebrate flavor, culture, and identity while connecting the local community to new culinary experiences.",
        "about_text": "Flavors of Brazil Food Festival is a dining circuit that brings Brazilian restaurants together across Georgia to promote national cuisine, generate visibility, and strengthen the presence of the Brazilian culinary community. This first edition is promotional and collaborative, with no competition, voting, or ranking.",
        "dates_tbd": "Dates to be announced",
        "footer_contact": "Contact",
        "footer_social": "Social media",
        "footer_legal": "Legal",
        "footer_rights": "All rights reserved.",
        "menu_open": "Open menu",
        "hero_scroll": "scroll",
        "stat_days": "Days",
        "stat_restaurants": "Restaurants",
        "stat_brazilian": "Brazilian Cuisine",
        "about_label": "About the festival",
        "about_title": "A Brazilian dining circuit in Georgia",
        "objectives_label": "Goals",
        "objectives_title": "Visibility, culture, and community",
        "objective_promote_title": "Promote",
        "objective_promote_text": "Brazilian cuisine in Georgia.",
        "objective_expand_title": "Expand",
        "objective_expand_text": "The exposure of participating restaurants.",
        "objective_media_title": "Generate media",
        "objective_media_text": "Digital content, social media, and editorial promotion.",
        "objective_position_title": "Position",
        "objective_position_text": "Restaurants as references within the community.",
        "why_label": "Why participate",
        "why_title": "A commercial showcase for Brazilian restaurants",
        "why_1": "More visibility for your business",
        "why_2": "Attract new customers",
        "why_3": "Media and social media promotion",
        "why_4": "Strengthen your restaurant brand",
        "why_5": "Official participation certificate",
        "why_6": "Presence on the official festival website",
        "who_label": "Who can participate",
        "who_title": "Legal businesses operating in Georgia",
        "who_1": "Brazilian restaurants",
        "who_2": "Bars",
        "who_3": "Cafes",
        "who_4": "Bakeries",
        "who_5": "Dessert shops",
        "who_6": "Food trucks",
        "how_label": "How it works",
        "how_title": "Simple steps to join the circuit",
        "how_duration": "Expected duration: approximately 20 days / 3 to 4 weeks.",
        "step_create_title": "Create",
        "step_create_text": "The restaurant creates a special dish or menu.",
        "step_define_title": "Set",
        "step_define_text": "Defines a fixed price for the experience.",
        "step_offer_title": "Offer",
        "step_offer_text": "Makes the dish available throughout the festival period.",
        "step_promote_title": "Promote",
        "step_promote_text": "Uses official materials as a participant.",
        "step_receive_title": "Welcome",
        "step_receive_text": "Welcomes customers and gains visibility.",
        "services_label": "Included services",
        "services_title": "Content, website, and certificate",
        "service_1": "Production of 1 video at the restaurant featuring the festival dish.",
        "service_2": "Content published on Business News TV and Viver Magazine social media.",
        "service_3": "Restaurant listing on the official festival page.",
        "service_4": "Official participation certificate.",
        "service_5": "Digital content such as posts, stories, and reels.",
        "media_label": "Content production",
        "media_title": "Scheduled filming at the restaurant",
        "media_text": "The organization will film at the restaurant on a previously scheduled date. The produced content may be used on social media, promotional materials, and institutional festival promotion.",
        "certificate_label": "Certificate",
        "certificate_title": "Official Participation Certificate",
        "certificate_text": "All approved participants will receive an Official Participation Certificate for the Flavors of Brazil Food Festival - Georgia Edition. The certificate will be issued by Business News TV and Viver Magazine.",
        "responsibilities_label": "Responsibilities",
        "responsibilities_title": "Participant restaurant commitments",
        "responsibility_1": "Keep the dish/menu available throughout the festival.",
        "responsibility_2": "Ensure product quality and consistency.",
        "responsibility_3": "Provide accurate price and description information.",
        "responsibility_4": "Use official festival materials.",
        "responsibility_5": "Collaborate with promotion.",
        "fee_label": "Participation fee",
        "fee_title": "US$650 per restaurant",
        "fee_text": "One-time participation fee. Payment will be requested after application approval.",
        "process_label": "Application process",
        "process_title": "From application to promotion",
        "process_1": "Complete the application form on the website.",
        "process_2": "Send dish/menu information.",
        "process_3": "Go through curation.",
        "process_4": "Pay the application fee.",
        "process_5": "Receive confirmation.",
        "process_6": "Start promoting.",
        "schedule_label": "Schedule",
        "schedule_title": "Dates to be announced",
        "schedule_applications_label": "Applications open",
        "schedule_production_label": "Content production period",
        "schedule_start_label": "Festival starts",
        "schedule_end_label": "Festival ends",
        "restaurants_label": "Dining Circuit",
        "restaurants_page_text": "Restaurants approved by the curation team for Flavors of Brazil Food Festival - Georgia Edition 2026.",
        "contact_label": "Contact",
        "contact_title": "Talk to the organization",
        "back_home": "Back to website",
        "legal_label": "Legal",
        "terms_title": "Participation terms",
        "terms_1": "Applications are subject to curation by the Flavors of Brazil Food Festival - Georgia Edition 2026 organization.",
        "terms_2": "The participation fee will only be requested after application approval.",
        "terms_3": "Use of the festival brand is restricted to approved and confirmed participants.",
        "terms_4": "The organization may approve or decline applications according to editorial, commercial, and operational criteria.",
        "terms_5": "Failure to follow participation guidelines may result in removal from the festival.",
        "terms_6": "The festival is promotional and collaborative, with no public voting, ranking, or competition.",
        "privacy_title": "Privacy policy",
        "privacy_1": "Data submitted through the form will be used for application review, curation, communication with responsible contacts, and festival operations.",
        "privacy_2": "Approved restaurant data, such as name, address, phone, website, Instagram, hours, dish, description, price, and images, may be published on the official website.",
        "privacy_3": "Images, videos, and restaurant or dish information may be used to promote Flavors of Brazil Food Festival - Georgia Edition 2026.",
        "privacy_4": "Sensitive administrative access data is not published and must be kept in secure environment variables.",
        "apply_intro": "Fill in the responsible contact, restaurant, and special dish/menu details for curation.",
        "responsible_data": "Responsible contact",
        "restaurant_data": "Restaurant information",
        "dish_data": "Dish/menu information",
        "required_acceptances": "Required acceptances",
        "full_name": "Full name",
        "role": "Title/role",
        "phone": "Phone",
        "email": "Email",
        "restaurant_name": "Restaurant name",
        "business_type": "Business type",
        "select_option": "Select",
        "full_address": "Full address",
        "city": "City",
        "state": "State",
        "zip_code": "ZIP code",
        "business_phone": "Business phone",
        "website": "Website",
        "instagram": "Instagram",
        "facebook": "Facebook",
        "business_hours": "Business hours",
        "legal_question": "Is the business legal and operating in Georgia?",
        "dish_name_label": "Dish or special menu name",
        "fixed_price": "Fixed price",
        "category": "Category",
        "available_question": "Will the dish be available throughout the festival?",
        "dish_description_label": "Dish/menu description",
        "main_ingredients": "Main ingredients",
        "allergens_label": "Contains allergens?",
        "dish_upload": "Dish photo upload",
        "additional_notes": "Additional notes",
        "submit_application": "Submit application",
        "accept_truth_text": "I confirm that the information provided is true.",
        "accept_curation_text": "I confirm that the restaurant may go through curation before approval.",
        "accept_fee_text": "I understand that the participation fee is US$650 per restaurant.",
        "accept_brand_text": "I understand that use of the festival brand is restricted to approved participants.",
        "accept_media_text": "I authorize the use of restaurant/dish images, videos, and information for festival promotion.",
        "accept_responsibilities_text": "I agree with the participant restaurant responsibilities.",
        "yes": "Yes",
        "no": "No",
        "undefined": "To be announced",
        "address": "Address",
        "hours": "Hours",
        "business_Restaurante": "Restaurant",
        "business_Bar": "Bar",
        "business_Cafe": "Cafe",
        "business_Padaria": "Bakery",
        "business_Doceria": "Dessert shop",
        "business_Food truck": "Food truck",
        "business_Outro": "Other",
        "dish_Prato principal": "Main dish",
        "dish_Lanche": "Snack",
        "dish_Sobremesa": "Dessert",
        "dish_Bebida": "Drink",
        "dish_Combo": "Combo",
        "dish_Outro": "Other",
        "error_required": "Required field.",
        "error_email": "Enter a valid email address.",
        "error_business_type": "Select a valid business type.",
        "error_dish_category": "Select a valid category.",
        "error_yes_no": "Select Yes or No.",
        "error_accept": "Required acceptance.",
        "error_upload_image": "Upload a JPG, PNG, or WebP image.",
    },
    "es-ES": {
        "nav_festival": "Festival",
        "nav_restaurants": "Restaurantes",
        "nav_apply": "Inscripcion",
        "nav_admin": "Admin",
        "cta_apply": "Inscribir mi restaurante",
        "cta_how": "Como funciona",
        "official_badge": "Participante Oficial",
        "view_restaurant": "Ver restaurante",
        "view_map": "Ver en el mapa",
        "contact": "Contactar",
        "restaurants_title": "Restaurantes participantes",
        "restaurants_empty": "Los restaurantes aprobados apareceran aqui pronto.",
        "apply_title": "Inscripcion de restaurante",
        "thank_you_title": "Inscripcion recibida con exito.",
        "thank_you_text": "La organizacion se pondra en contacto despues de la curaduria.",
        "terms": "Terminos",
        "privacy": "Privacidad",
        "festival_edition": "Georgia Edition 2026",
        "homepage_title": "Flavors of Brazil Food Festival Georgia Edition 2026",
        "homepage_description": "Festival gastronomico brasileno en Georgia que reune restaurantes, sabores, cultura y experiencias culinarias brasilenas.",
        "hero_title": "Flavors of Brazil Food Festival - Georgia Edition 2026",
        "hero_subtitle": "Una experiencia gastronomica brasilena en Georgia",
        "hero_text": "Un circuito gastronomico que reune restaurantes brasilenos para celebrar sabores, cultura e identidad, conectando a la comunidad local con nuevas experiencias culinarias.",
        "about_text": "Flavors of Brazil Food Festival es un circuito gastronomico que reune restaurantes brasilenos en la region de Georgia, con el objetivo de promover la cocina nacional, generar visibilidad y fortalecer la presencia de la comunidad gastronomica brasilena. Esta primera edicion tendra caracter promocional y colaborativo, sin competencia, votacion ni ranking.",
        "dates_tbd": "Fechas por definir",
        "footer_contact": "Contacto",
        "footer_social": "Redes sociales",
        "footer_legal": "Legal",
        "footer_rights": "Todos los derechos reservados.",
        "menu_open": "Abrir menu",
        "hero_scroll": "scroll",
        "stat_days": "Dias",
        "stat_restaurants": "Restaurantes",
        "stat_brazilian": "Gastronomia Brasilena",
        "about_label": "Sobre el festival",
        "about_title": "Un circuito brasileno en Georgia",
        "objectives_label": "Objetivos",
        "objectives_title": "Visibilidad, cultura y comunidad",
        "objective_promote_title": "Promover",
        "objective_promote_text": "La gastronomia brasilena en Georgia.",
        "objective_expand_title": "Ampliar",
        "objective_expand_text": "La exposicion de los restaurantes participantes.",
        "objective_media_title": "Generar medios",
        "objective_media_text": "Contenido digital, redes sociales y divulgacion editorial.",
        "objective_position_title": "Posicionar",
        "objective_position_text": "Restaurantes como referencia dentro de la comunidad.",
        "why_label": "Por que participar",
        "why_title": "Una vitrina comercial para restaurantes brasilenos",
        "why_1": "Mas visibilidad para su negocio",
        "why_2": "Atraccion de nuevos clientes",
        "why_3": "Divulgacion en medios y redes sociales",
        "why_4": "Fortalecimiento de la marca del restaurante",
        "why_5": "Certificado oficial de participacion",
        "why_6": "Presencia en el sitio web oficial del festival",
        "who_label": "Quien puede participar",
        "who_title": "Negocios legalizados en Georgia",
        "who_1": "Restaurantes brasilenos",
        "who_2": "Bares",
        "who_3": "Cafes",
        "who_4": "Panaderias",
        "who_5": "Dulcerias",
        "who_6": "Food trucks",
        "how_label": "Como funciona",
        "how_title": "Etapas simples para entrar al circuito",
        "how_duration": "Duracion prevista: aproximadamente 20 dias / 3 a 4 semanas.",
        "step_create_title": "Crear",
        "step_create_text": "El restaurante crea un plato o menu especial.",
        "step_define_title": "Definir",
        "step_define_text": "Define un precio fijo para la experiencia.",
        "step_offer_title": "Ofrecer",
        "step_offer_text": "Ofrece el plato durante todo el periodo del festival.",
        "step_promote_title": "Divulgar",
        "step_promote_text": "Usa los materiales oficiales como participante.",
        "step_receive_title": "Recibir",
        "step_receive_text": "Recibe clientes y gana visibilidad.",
        "services_label": "Servicios incluidos",
        "services_title": "Contenido, sitio web y certificado",
        "service_1": "Produccion de 1 video en el restaurante mostrando el plato del festival.",
        "service_2": "Publicacion de contenido en las redes sociales de Business News TV y Viver Magazine.",
        "service_3": "Insercion del restaurante en la pagina oficial del festival.",
        "service_4": "Certificado oficial de participacion.",
        "service_5": "Contenidos digitales como posts, stories y reels.",
        "media_label": "Produccion de contenido",
        "media_title": "Grabacion agendada en el restaurante",
        "media_text": "La organizacion realizara la grabacion de video en el restaurante en una fecha previamente agendada. El contenido producido podra usarse en redes sociales, materiales promocionales y divulgacion institucional del festival.",
        "certificate_label": "Certificado",
        "certificate_title": "Certificado Oficial de Participacion",
        "certificate_text": "Todos los participantes aprobados recibiran el Certificado Oficial de Participacion de Flavors of Brazil Food Festival - Georgia Edition. El certificado sera emitido por Business News TV y Viver Magazine.",
        "responsibilities_label": "Responsabilidades",
        "responsibilities_title": "Compromisos del restaurante participante",
        "responsibility_1": "Mantener el plato/menu disponible durante todo el festival.",
        "responsibility_2": "Garantizar calidad y consistencia del producto.",
        "responsibility_3": "Informar correctamente precio y descripcion.",
        "responsibility_4": "Utilizar los materiales oficiales del festival.",
        "responsibility_5": "Colaborar con la divulgacion.",
        "fee_label": "Tasa de participacion",
        "fee_title": "US$650 por restaurante",
        "fee_text": "Tasa unica de participacion. El pago sera solicitado despues de la aprobacion de la inscripcion.",
        "process_label": "Proceso de inscripcion",
        "process_title": "De la aplicacion a la divulgacion",
        "process_1": "Completar el formulario de inscripcion en el sitio.",
        "process_2": "Enviar informacion del plato/menu.",
        "process_3": "Pasar por curaduria.",
        "process_4": "Pagar la tasa de inscripcion.",
        "process_5": "Recibir confirmacion.",
        "process_6": "Comenzar a divulgar.",
        "schedule_label": "Cronograma",
        "schedule_title": "Fechas por definir",
        "schedule_applications_label": "Apertura de inscripciones",
        "schedule_production_label": "Periodo de produccion de contenido",
        "schedule_start_label": "Inicio del festival",
        "schedule_end_label": "Cierre",
        "restaurants_label": "Circuito Gastronomico",
        "restaurants_page_text": "Restaurantes aprobados por la curaduria de Flavors of Brazil Food Festival - Georgia Edition 2026.",
        "contact_label": "Contacto",
        "contact_title": "Hable con la organizacion",
        "back_home": "Volver al sitio",
        "legal_label": "Legal",
        "terms_title": "Terminos de participacion",
        "terms_1": "La inscripcion esta sujeta a curaduria de la organizacion de Flavors of Brazil Food Festival - Georgia Edition 2026.",
        "terms_2": "La tasa de participacion sera solicitada solamente despues de la aprobacion de la inscripcion.",
        "terms_3": "El uso de la marca del festival esta restringido a participantes aprobados y confirmados.",
        "terms_4": "La organizacion puede aprobar o rechazar inscripciones segun criterios editoriales, comerciales y operativos.",
        "terms_5": "El incumplimiento de las directrices de participacion puede resultar en exclusion del festival.",
        "terms_6": "El festival tiene caracter promocional y colaborativo, sin votacion, ranking o competencia publica.",
        "privacy_title": "Politica de privacidad",
        "privacy_1": "Los datos enviados en el formulario seran usados para evaluacion de la inscripcion, curaduria, comunicacion con responsables y operacion del festival.",
        "privacy_2": "Datos de restaurantes aprobados, como nombre, direccion, telefono, website, Instagram, horario, plato, descripcion, precio e imagenes, podran publicarse en el sitio oficial.",
        "privacy_3": "Imagenes, videos e informacion del restaurante o del plato podran usarse para divulgar Flavors of Brazil Food Festival - Georgia Edition 2026.",
        "privacy_4": "Datos sensibles de acceso administrativo no son publicados y deben mantenerse en variables de entorno seguras.",
        "apply_intro": "Complete los datos del responsable, del restaurante y del plato/menu especial para pasar por curaduria.",
        "responsible_data": "Datos del responsable",
        "restaurant_data": "Datos del restaurante",
        "dish_data": "Informacion del plato/menu",
        "required_acceptances": "Aceptaciones obligatorias",
        "full_name": "Nombre completo",
        "role": "Cargo/funcion",
        "phone": "Telefono",
        "email": "E-mail",
        "restaurant_name": "Nombre del restaurante",
        "business_type": "Tipo de negocio",
        "select_option": "Seleccione",
        "full_address": "Direccion completa",
        "city": "Ciudad",
        "state": "Estado",
        "zip_code": "ZIP code",
        "business_phone": "Telefono comercial",
        "website": "Website",
        "instagram": "Instagram",
        "facebook": "Facebook",
        "business_hours": "Horario de funcionamiento",
        "legal_question": "El negocio esta legalizado y en funcionamiento en Georgia?",
        "dish_name_label": "Nombre del plato o menu especial",
        "fixed_price": "Precio fijo",
        "category": "Categoria",
        "available_question": "El plato estara disponible durante todo el festival?",
        "dish_description_label": "Descripcion del plato/menu",
        "main_ingredients": "Ingredientes principales",
        "allergens_label": "Contiene alergenos?",
        "dish_upload": "Subida de foto del plato",
        "additional_notes": "Observaciones adicionales",
        "submit_application": "Enviar inscripcion",
        "accept_truth_text": "Confirmo que la informacion proporcionada es verdadera.",
        "accept_curation_text": "Confirmo que el restaurante podra pasar por curaduria antes de la aprobacion.",
        "accept_fee_text": "Entiendo que la tasa de participacion es de US$650 por restaurante.",
        "accept_brand_text": "Entiendo que el uso de la marca del festival esta restringido a participantes aprobados.",
        "accept_media_text": "Autorizo el uso de imagenes, videos e informacion del restaurante/plato para divulgacion del festival.",
        "accept_responsibilities_text": "Acepto las responsabilidades del restaurante participante.",
        "yes": "Si",
        "no": "No",
        "undefined": "Por definir",
        "address": "Direccion",
        "hours": "Horario",
        "business_Restaurante": "Restaurante",
        "business_Bar": "Bar",
        "business_Cafe": "Cafe",
        "business_Padaria": "Panaderia",
        "business_Doceria": "Dulceria",
        "business_Food truck": "Food truck",
        "business_Outro": "Otro",
        "dish_Prato principal": "Plato principal",
        "dish_Lanche": "Snack",
        "dish_Sobremesa": "Postre",
        "dish_Bebida": "Bebida",
        "dish_Combo": "Combo",
        "dish_Outro": "Otro",
        "error_required": "Campo obligatorio.",
        "error_email": "Informe un e-mail valido.",
        "error_business_type": "Seleccione un tipo valido.",
        "error_dish_category": "Seleccione una categoria valida.",
        "error_yes_no": "Seleccione Si o No.",
        "error_accept": "Aceptacion obligatoria.",
        "error_upload_image": "Suba una imagen JPG, PNG o WebP.",
    },
}


DEFAULT_SETTINGS = {
    "festival_name": "Flavors of Brazil Food Festival",
    "festival_edition": "Georgia Edition 2026",
    "homepage_title": "Flavors of Brazil Food Festival Georgia Edition 2026",
    "homepage_description": (
        "Festival gastronomico brasileiro na Georgia reunindo restaurantes, "
        "sabores, cultura e experiencias culinarias brasileiras."
    ),
    "hero_title": "Flavors of Brazil Food Festival - Georgia Edition 2026",
    "hero_subtitle": "Uma experiencia gastronomica brasileira na Georgia",
    "hero_text": (
        "Um circuito gastronomico que reune restaurantes brasileiros para celebrar "
        "sabores, cultura e identidade, conectando a comunidade local a novas "
        "experiencias culinarias."
    ),
    "about_text": (
        "O Flavors of Brazil Food Festival e um circuito gastronomico que reune "
        "restaurantes brasileiros na regiao da Georgia, com o objetivo de promover "
        "a culinaria nacional, gerar visibilidade e fortalecer a presenca da "
        "comunidade gastronomica brasileira. Esta primeira edicao tera carater "
        "promocional e colaborativo, sem competicao, votacao ou ranking."
    ),
    "schedule_applications": "Datas a definir",
    "schedule_production": "Datas a definir",
    "schedule_start": "Datas a definir",
    "schedule_end": "Datas a definir",
    "contact_rodrigo_name": "Rodrigo Souto Souza",
    "contact_rodrigo_phone": "(770) 873-6319",
    "contact_rodrigo_email": "rsouza@greatstoriesfilms.com",
    "contact_dilla_name": "Dilla Campos",
    "contact_dilla_phone": "(770) 953-4250",
    "contact_dilla_email": "vivermagazine@gmail.com",
    "instagram_business": "@businessbrazil.usa",
    "instagram_rodrigo": "@rodrigosoutosouza",
    "instagram_viver": "@vivermagazine",
    "instagram_dilla": "@dillacampos",
}


def translate(lang, key):
    bundle = TRANSLATIONS.get(lang, TRANSLATIONS[DEFAULT_LANGUAGE])
    return bundle.get(key, TRANSLATIONS[DEFAULT_LANGUAGE].get(key, key))


def localize_settings(settings, lang):
    localized = dict(settings)
    if lang == DEFAULT_LANGUAGE:
        return localized
    bundle = TRANSLATIONS.get(lang, {})
    for key in DEFAULT_SETTINGS:
        if key in bundle:
            localized[key] = bundle[key]
    for key in (
        "schedule_applications",
        "schedule_production",
        "schedule_start",
        "schedule_end",
    ):
        if localized.get(key) == DEFAULT_SETTINGS.get(key):
            localized[key] = translate(lang, "dates_tbd")
    return localized


def option_label(lang, value):
    for prefix in ("business", "dish"):
        key = f"{prefix}_{value}"
        translated = translate(lang, key)
        if translated != key:
            return translated
    return value
